# -*- coding: utf-8 -*-
"""10 районов Бали для SEO. Порядок = приоритет (подсказки Google «услуга + район», 25.09.2026:
Ubud 23, Canggu 23, Sanur 18, Uluwatu 17, Kuta 14, Seminyak 12, Jimbaran 12, Denpasar 9, Nusa Dua 7, Kerobokan/Umalas 3+3).
Особенности — общие для района условия, без цифр и обещаний; уточнить у мастера."""

AREAS = [
 {"slug": "canggu", "photo": "photo-1721984288541-96b644c716d5", "en": "Canggu", "ru": "Чангу", "map": "Canggu, Bali",
  "subs": ["Berawa", "Batu Bolong", "Echo Beach", "Pererenan", "Babakan", "Padonan"],
  "intro": {"en": "Canggu grew fast from rice fields into villas, cafes and co-living. New builds, high groundwater and heavy rain shape most call-outs here.",
            "ru": "Чангу быстро вырос из рисовых полей в район вилл, кафе и коливингов. Новостройки, высокие грунтовые воды и ливни определяют большинство вызовов."},
  "issues": {"en": [["Built fast, fixed often", "Many villas went up quickly. Hidden leaks, loose fittings and poorly sloped drains often show up in the first years."],
                    ["Rice-field groundwater", "Former paddies mean a high water table: septic tanks fill faster and drains back up after rain."],
                    ["Rainy-season flooding", "Streets and gardens flood in heavy rain. Pumps, pool overflows and pump rooms need checking before the season."],
                    ["Pools everywhere", "Almost every rental has a pool. Leaves from surrounding fields and daily guests mean weekly service matters."]],
             "ru": [["Строили быстро — чинят часто", "Многие виллы возведены в спешке. Скрытые протечки, слабые соединения и сливы без уклона проявляются в первые годы."],
                    ["Грунтовые воды рисовых полей", "На месте бывших полей высокий уровень воды: септики заполняются быстрее, после дождя сливы подтапливает."],
                    ["Подтопления в сезон дождей", "В ливни затапливает улицы и сады. Насосы, переливы бассейнов и техкомнаты стоит проверить до сезона."],
                    ["Бассейн почти в каждой вилле", "Листья с полей и постоянные гости — регулярное обслуживание бассейна здесь особенно важно."]]}},
 {"slug": "ubud", "photo": "photo-1555400038-63f5ba517a47", "en": "Ubud", "ru": "Убуд", "map": "Ubud, Bali",
  "subs": ["Penestanan", "Sayan", "Nyuh Kuning", "Peliatan", "Tegallalang", "Mas"],
  "intro": {"en": "Ubud is jungle, river valleys and humidity. Villas on slopes, spring and well water and constant leaf fall change how plumbing and pools behave.",
            "ru": "Убуд — джунгли, долины рек и высокая влажность. Виллы на склонах, родниковая и колодезная вода и постоянный листопад влияют на сантехнику и бассейны."},
  "issues": {"en": [["Humidity and mould", "Damp air means mould in bathrooms, swollen doors and corroded fittings. Ventilation and good sealing matter."],
                    ["Slopes and pressure", "Villas on hillsides often rely on pumps and tanks; pressure problems and air in pipes are common."],
                    ["Leaves and jungle", "Pools and gutters fill with leaves daily. Skimmers, filters and drains clog faster than on the coast."],
                    ["Well and spring water", "Many homes use wells or springs. Filters and UV systems need regular service."]],
             "ru": [["Влажность и плесень", "Сырой воздух — это плесень в ванных, разбухшие двери и коррозия арматуры. Важны вентиляция и герметизация."],
                    ["Склоны и давление", "Виллы на склонах часто зависят от насосов и баков: проблемы с напором и воздух в трубах — обычное дело."],
                    ["Листья и джунгли", "Бассейны и водостоки ежедневно засыпает листьями. Скиммеры, фильтры и сливы забиваются быстрее, чем у моря."],
                    ["Колодцы и родники", "Многие дома на колодезной или родниковой воде. Фильтрам и УФ-стерилизаторам нужно регулярное обслуживание."]]}},
 {"slug": "seminyak", "photo": "photo-1571984405176-5958bd9ac31d", "en": "Seminyak", "ru": "Семиньяк", "map": "Seminyak, Bali",
  "subs": ["Petitenget", "Oberoi", "Basangkasa", "Batu Belig", "Drupadi"],
  "intro": {"en": "Seminyak is dense: villas close together, older infrastructure and busy rentals. Quick fixes between guests are the norm.",
            "ru": "Семиньяк плотно застроен: виллы близко друг к другу, старая инфраструктура и постоянные гости. Здесь ценится быстрый ремонт между заездами."},
  "issues": {"en": [["Older villas", "Many villas are 15–25 years old: tired pipework, old heaters and worn pool equipment."],
                    ["Busy rentals", "High occupancy means blocked toilets, broken mixers and hot-water complaints need fixing between check-ins."],
                    ["Street flooding", "Heavy rain floods lanes and overloads drains and septic systems."],
                    ["Tight spaces", "Small plots and shared walls make leak detection and pump rooms harder to reach."]],
             "ru": [["Старые виллы", "Многим виллам 15–25 лет: уставшие трубы, старые бойлеры, изношенное оборудование бассейнов."],
                    ["Загруженная аренда", "Высокая загрузка — засоры, сломанные смесители и жалобы на горячую воду нужно чинить между заездами."],
                    ["Подтопления улиц", "В ливни затапливает переулки, перегружаются сливы и септики."],
                    ["Тесная застройка", "Маленькие участки и общие стены усложняют поиск протечек и доступ к техкомнатам."]]}},
 {"slug": "uluwatu", "photo": "photo-1664918706173-6349ca225dd0", "en": "Uluwatu", "ru": "Улувату", "map": "Uluwatu, Bali",
  "subs": ["Bingin", "Padang Padang", "Pecatu", "Ungasan", "Balangan", "Labuan Sait"],
  "intro": {"en": "Uluwatu sits on the dry limestone Bukit. Water supply, tanks and pumps are the main story here — plus salt wind on cliff-top villas.",
            "ru": "Улувату стоит на сухом известняковом плато Букит. Главное здесь — водоснабжение, баки и насосы, а ещё солёный ветер на виллах у обрывов."},
  "issues": {"en": [["Water supply", "Mains water is limited in many parts of the Bukit. Villas rely on tanks, deep wells and water deliveries — tanks and float valves matter."],
                    ["Pumps work hard", "Long pipe runs and big tanks mean pumps and pressure switches wear out faster."],
                    ["Salt wind", "Cliff-top villas get salt spray: taps, pool equipment and metal fittings corrode quickly."],
                    ["Hard water", "Limestone water leaves scale on heaters, shower heads and pool tiles."]],
             "ru": [["Водоснабжение", "Городская вода есть не везде на Буките. Виллы живут на баках, глубоких скважинах и привозной воде — баки и поплавковые клапаны критичны."],
                    ["Насосы на износ", "Длинные трассы и большие баки — насосы и реле давления изнашиваются быстрее."],
                    ["Солёный ветер", "Виллы у обрывов ловят солёные брызги: смесители, оборудование бассейна и металл быстро ржавеют."],
                    ["Жёсткая вода", "Известняковая вода оставляет накипь в бойлерах, лейках и на плитке бассейнов."]]}},
 {"slug": "sanur", "photo": "photo-1733281120655-8da3dc371514", "en": "Sanur", "ru": "Санур", "map": "Sanur, Denpasar Selatan, Bali",
  "subs": ["Sanur Kaja", "Sanur Kauh", "Sindhu", "Semawang", "Mertasari", "Batujimbar"],
  "intro": {"en": "Sanur is calm and established: older villas, long-term residents and homes close to the beach. Ageing pipework and salt air are the common threads.",
            "ru": "Санур — спокойный и обжитой район: старые виллы, долгосрочные жители, дома у пляжа. Стареющие трубы и морской воздух — общая тема."},
  "issues": {"en": [["Villas 15–20 years old", "Original PVC pipework and fittings turn brittle in the sun; replacing a section is often smarter than patching."],
                    ["Salt air near the beach", "In Sindhu, Semawang and Mertasari the sea air corrodes taps, hinges and pump motors fast."],
                    ["Well water and PDAM", "Near the sea well water can be brackish — filters clog faster and heaters build scale."],
                    ["Septic tanks", "Small tanks and narrow pipes: blockages and smells usually mean paper, grease or an overdue pump-out."]],
             "ru": [["Виллам 15–20 лет", "Родные трубы PVC на солнце становятся хрупкими; часто разумнее заменить участок, чем латать."],
                    ["Морской воздух у пляжа", "В Синду, Семаванге и Мертасари морской воздух быстро разъедает смесители, петли и моторы насосов."],
                    ["Скважина и PDAM", "У моря вода из скважины бывает солоноватой — фильтры забиваются быстрее, в бойлерах накипь."],
                    ["Септики", "Маленькие септики и узкие трубы: засоры и запах — это бумага, жир или давно не откачанный септик."]]}},
 {"slug": "jimbaran", "photo": "photo-1575498685808-db3dcba64345", "en": "Jimbaran", "ru": "Джимбаран", "map": "Jimbaran, Bali",
  "subs": ["Jimbaran Bay", "Kedonganan", "Bukit Jimbaran", "Goa Gong", "Kelan"],
  "intro": {"en": "Jimbaran mixes bay-side homes and hillside villas on the edge of the Bukit — both salt air and water-supply issues show up here.",
            "ru": "В Джимбаране дома у залива соседствуют с виллами на склонах Букита — здесь встречаются и морская коррозия, и проблемы с водоснабжением."},
  "issues": {"en": [["Hillside water pressure", "Villas up the hill depend on tanks and pumps; low pressure and pumps cycling are frequent."],
                    ["Hard water", "Scale builds up in heaters, mixers and pool equipment."],
                    ["Bay-side corrosion", "Near the beach salt air shortens the life of fittings and pumps."],
                    ["Family villas with pools", "Larger family homes mean more bathrooms, bigger pools and more equipment to maintain."]],
             "ru": [["Напор на склонах", "Виллы на холме зависят от баков и насосов; слабый напор и частые включения насоса — обычная история."],
                    ["Жёсткая вода", "Накипь копится в бойлерах, смесителях и оборудовании бассейна."],
                    ["Коррозия у залива", "У пляжа морской воздух сокращает жизнь арматуры и насосов."],
                    ["Семейные виллы с бассейнами", "Большие дома — больше санузлов, крупнее бассейны и больше оборудования в обслуживании."]]}},
 {"slug": "kuta-legian", "photo": "photo-1657982217612-eb18e2ab4312", "en": "Kuta & Legian", "ru": "Кута и Легиан", "map": "Kuta, Bali",
  "subs": ["Kuta", "Legian", "Tuban", "Kuta Beach", "Jl. Padma"],
  "intro": {"en": "Kuta and Legian are Bali's oldest tourist streets: guesthouses, small hotels and older homes where plumbing has seen decades of use.",
            "ru": "Кута и Легиан — старейшие туристические улицы Бали: гестхаусы, небольшие отели и старые дома, где сантехника прослужила десятилетия."},
  "issues": {"en": [["Old infrastructure", "Decades-old pipes, drains and septic systems — blockages and leaks are the most common calls."],
                    ["Guesthouses and small hotels", "Many rooms, many bathrooms: toilets, mixers and water heaters wear out fast."],
                    ["Flooding lanes", "Low-lying streets flood in heavy rain and drains back up."],
                    ["Salt air", "Close to the beach metal fittings corrode quickly."]],
             "ru": [["Старая инфраструктура", "Трубам, сливам и септикам десятки лет — засоры и протечки здесь самые частые вызовы."],
                    ["Гестхаусы и мини-отели", "Много номеров — много санузлов: унитазы, смесители и бойлеры изнашиваются быстро."],
                    ["Подтопление переулков", "Низкие улицы затапливает в ливни, сливы подпирает."],
                    ["Морской воздух", "У пляжа металлическая арматура быстро ржавеет."]]}},
 {"slug": "nusa-dua", "photo": "photo-1609391061565-622f94e736e9", "en": "Nusa Dua", "ru": "Нуса Дуа", "map": "Nusa Dua, Bali",
  "subs": ["Tanjung Benoa", "Bualu", "Sawangan", "Kampial", "Peminge"],
  "intro": {"en": "Nusa Dua is resorts, gated estates and spacious villas. Owners expect hotel-level standards for pools and bathrooms.",
            "ru": "Нуса Дуа — курорты, закрытые комплексы и просторные виллы. Владельцы ждут гостиничного уровня от бассейнов и ванных."},
  "issues": {"en": [["Large pools", "Big pools, overflows and water features need regular balancing and equipment checks."],
                    ["Gated estates", "Complexes have their own rules and access — scheduling work in advance helps."],
                    ["Salt air and hard water", "Coastal air and Bukit water mean corrosion and scale on fittings and heaters."],
                    ["High standards", "Guests notice every drip and every cloudy pool — preventive service pays off."]],
             "ru": [["Большие бассейны", "Крупные бассейны, переливы и фонтаны требуют регулярного баланса воды и проверки оборудования."],
                    ["Закрытые комплексы", "У комплексов свои правила и пропуска — работы лучше планировать заранее."],
                    ["Морской воздух и жёсткая вода", "Побережье и вода Букита — коррозия и накипь на арматуре и бойлерах."],
                    ["Высокие ожидания", "Гости замечают каждую каплю и мутную воду — профилактика окупается."]]}},
 {"slug": "denpasar", "photo": "photo-1501179691627-eeaa65ea017c", "en": "Denpasar", "ru": "Денпасар", "map": "Denpasar, Bali",
  "subs": ["Renon", "Sidakarya", "Panjer", "Sesetan", "Kesiman", "Denpasar Barat"],
  "intro": {"en": "Denpasar is Bali's city: family houses, shop-houses and offices on PDAM mains, with tight streets and older drainage.",
            "ru": "Денпасар — город Бали: семейные дома, ру-хаусы и офисы на городской воде PDAM, узкие улицы и старая ливнёвка."},
  "issues": {"en": [["PDAM interruptions", "Mains supply can drop; tanks, float valves and pumps keep houses running."],
                    ["Shop-houses and offices", "Shared plumbing and busy toilets mean regular blockages."],
                    ["Older drainage", "City drains overflow in heavy rain and push water back into homes."],
                    ["Water heaters", "Electric and gas heaters in family homes need regular service."]],
             "ru": [["Перебои PDAM", "Городская вода может пропадать; баки, поплавковые клапаны и насосы держат дом на плаву."],
                    ["Ру-хаусы и офисы", "Общие стояки и загруженные туалеты — регулярные засоры."],
                    ["Старая ливнёвка", "Городские стоки переполняются в ливни и подтапливают дома."],
                    ["Бойлеры", "Электрическим и газовым бойлерам в семейных домах нужно регулярное обслуживание."]]}},
 {"slug": "kerobokan-umalas", "photo": "photo-1569881347427-c861051db3f9", "en": "Kerobokan & Umalas", "ru": "Керобокан и Умалас", "map": "Umalas, Bali",
  "subs": ["Kerobokan Kelod", "Kerobokan Kaja", "Umalas", "Banjar Anyar", "Batu Belig"],
  "intro": {"en": "Kerobokan and Umalas are quieter villa areas between Seminyak and Canggu — long-term rentals, families and bigger gardens.",
            "ru": "Керобокан и Умалас — тихие районы вилл между Семиньяком и Чангу: долгосрочная аренда, семьи и большие сады."},
  "issues": {"en": [["Long-term villas", "Families living full-time put steady load on heaters, pumps and septic tanks."],
                    ["Gardens and irrigation", "Bigger gardens mean irrigation leaks, pumps and drainage to maintain."],
                    ["Rice-field water table", "Like Canggu, groundwater is high — septic tanks and drains need attention after rain."],
                    ["Mixed-age villas", "Older villas sit next to new builds — both old-pipe and new-build issues appear."]],
             "ru": [["Долгосрочные виллы", "Семьи, живущие постоянно, дают постоянную нагрузку на бойлеры, насосы и септики."],
                    ["Сады и полив", "Большие сады — протечки полива, насосы и дренаж."],
                    ["Грунтовые воды", "Как и в Чангу, вода близко — септики и сливы требуют внимания после дождей."],
                    ["Виллы разного возраста", "Старые виллы соседствуют с новыми — встречаются проблемы и старых труб, и новостроек."]]}},
]

# какие особенности района показывать на странице «район × услуга»: индексы в issues
SERVICE_ISSUE = {"srv-santehnik": [0, 1], "srv-protechki": [0, 2], "srv-zasor": [1, 3], "srv-bojler": [2, 3], "srv-voda": [1, 2],
                 "srv-chistka-bassejna": [3, 2], "srv-obsluzhivanie-bassejna": [3, 0], "srv-oborudovanie-bassejna": [1, 3],
                 "srv-remont-bassejna": [0, 3], "srv-septik": [1, 2], "srv-melkij-remont": [0, 2], "srv-obsluzhivanie-villy": [2, 3]}
